### ISSUE TITLE
Camunda libraries missed. Command "grails war" vs "grails run-war" 

### ISSUE THREAD

**Issue by dariusralys** [plexiti/camunda-grails-plugin#43]
Hello,

With Intellij IDEA:
grails run-war 
camunda libraries in war exist
grails war 
camunda libraries in war not exist

How to fix it?

![grails war vs run-war](https://cloud.githubusercontent.com/assets/6286599/6634172/d453bfde-c95c-11e4-9279-a9943e8abce2.png)

**Comment by martinschimak** [comment]
Hi @dariusralys - when running grails war, grails uses the "prod" environment by default. In that scenario, the plugin assumes that you want to deploy the war to a camunda BPM tomcat with a pre-bundled "shared" process engine and does not bundle those libraries. (There is a possibility to override this behaviour, but I assume you won't need that)

I rather assume that you want to use an "embedded" engine in "prod", too. Now, for "prod" you need to configure it explicitely, it's described in the docs. Basically, this is a cautious strategy, because I don't want the plugin to e.g. upgrade database table schemas in "prod" environments without the user explicitely saying so. You find more information about how to do that in http://plexiti.github.io/camunda-grails-plugin/guide/deployment.html

Please feel free to reopen that question in case anything remains unclear. I will for the moment close it. Greetings, Martin.
