### ISSUE TITLE
Migrate plugin to a grails 3.x version

### ISSUE THREAD

**Issue by Luxor** [plexiti/camunda-grails-plugin#52]
Hi,

Thank you for the great plugin.
Do you plan to create grails 3 version in future

Regards

**Comment by martinschimak** [comment]
Hi @Luxor I already started to work on it. Many greetings.

**Comment by tolyo** [comment]
Awesome. Many thanks!

**Comment by Luxor** [comment]
Hi @martinschimak,

How it is going?

Many thanks for your work!!!

**Comment by martinschimak** [comment]
I had some difficulties (and lack of grails community support) to resolve some issues I had on my way of porting this plugin. Furthermore, I experienced changes in between small Grails 3.0.x releases which influenced the plugin behaviour. As I don't want to have to resolve issues here with the plugin because of grails 3 core changes, I decided to slow down further development a bit until the environment becomes more stable. However, I am now more positive about it and I think I will finish the work on the plugin in the coming weeks and release it as soon as I have the impression that everything (both grails 3 itself and the camunda plugin for 3) is stable enough.

**Comment by tolyo** [comment]
@martinschimak 

With Grails 3 being a Spring Boot app would it make sense to simply integrate with Camunda Engine Spring dependency then going the plugin route? Can we just reuse `camunda-engine-spring` with some preconfigured beans to align with version 2 of the plugin?

**Comment by meyerdan** [comment]
there is also a Spring boot integration (not sure how relevant that is to the issue)
https://github.com/camunda/camunda-bpm-spring-boot-starter

**Comment by tolyo** [comment]
@meyerdan 

Exactly. Activiti also has a Boot Starter.

**Comment by martinschimak** [comment]
Hi @tolyo - Grails 3 is based on Spring Boot, and Grails was always based on Spring. So using camunda-engine-spring is basically what the grails plugin does anyway - it just dynamically adds the spring beans in a way that makes your life as a grails application developer easier - e.g. with respect to configuration, test environment setup, war generation specifics. Therefore of course you can go the route to configure the camunda services as spring beans directly until the grails 3 plugin is released. The camunda user guide provides extensive guidance for doing that.

**Comment by tolyo** [comment]
@martinschimak 

Roger. I will try to see how Grails 3 works with Camunda Boot.

**Comment by Luxor** [comment]
@martinschimak 
Thank you for the updated

**Comment by Luxor** [comment]
Hi @tolyo, 
Did you succeed in integrating Grails 3 and Camunda Boot?

**Comment by tolyo** [comment]
@Luxor Working on it in the context of a Grails 3 migration for an existing app. Will let you know.

**Comment by nelcab** [comment]
Hi,

Any news regarding this matter?  We're planing to use this plug-in, but it would be interesting to know if ever would be a Grails 3.1.x or 3.2 version.  
Best regards,

N

**Comment by tolyo** [comment]
@nelcab Migrated to Camunda Spring (not the Boot version). Works fine.

**Comment by nelcab** [comment]
@tolyo nice to know that.  Our limitation is that Grails is our main framework of development on the company, due to rapid prototyping and dev processs, etc... we'll love to continue working on grails.  Hope @martinschimak would have news on this.  

Do actual version works good on Grails 2.5.x?

**Comment by martinschimak** [comment]
Hi all!

- Grails 2.5.x works with the existing version of the plugin

- I am still committed to migrate this. It's not a real small "piece of cake" because I have to think through the consequences of the cleaner separation of build and run time configuration in Grails 3 and its consequences for this plugin - and some other "small" but nasty little things that changed.

Actually I wanted to do it early, but was stopped by early issues with the Grails 3 framework. Now I just have the issue of priorities, this is community work and I have some other things I just need to finish first. So, I cannot promise a deadline right now, but as I said I am committed to do it.

As @nelcab pointed out, it's not difficult to get to run a Camunda / Spring configuration with grails. The main advantages of using the plugin is the better support for a grails like configuration, some defaults sensible to the typical needs of Grails dev/test/prod environments including support for test phases and a quite thorough documentation of all that. 

Many greetings and thanks for the patience!

**Comment by bruno-lopes** [comment]
Any news?

**Comment by nfahem** [comment]
Hi @martinschimak any news ?

**Comment by martinschimak** [comment]
Hi all. 

I really appreciate your ongoing interest in this plugin and its future. A lot. 
However, there is no work going on anymore in the direction of porting this plugin to grails 3.
I honestly did hope to find some time for that - somewhere out of the blue :-) - for too long, probably, because I invested quite a bit of work and enthusiasm here. But the hard truth is that I won't find the time in the foreseable future (which is for me 2017). And if you ask me, the odds are that I will never find that time again. Because: I currently do not use the grails stack anymore. I rather use e.g. Spring Boot - directly. Maybe you want to have a look at the awesome Camunda Spring Boot Plugin and start to directly use the Spring Boot stack yourself. Or: you fork this project and do the porting yourself! I encourage you to do that, however please start from scratch. The initial work I did to port the plugin to grails 3 is very probably obsolete and the troubles and problems I ran into back then (in the early days of grails 3) made me stop that work. But now a grails 3 port is probably much easier with grails 3 being mature. I therefore preserved my work on a separate branch, but moved the master branch back to the last grails 2 release. If you fork, please start from there. If you wish to learn from my branch, feel free to look at it. 

I wish you all the best and thank you for your interest, support and encouragement! Martin.
